defaults:
  - eniat
  - _self_

resume_dir: '/home/user/training_state/221225/'
keep_origin_path: False

task: fit_n_eval
type: torch

logger:
  type: StateLogger
  level: 10
  training_loss: epoch
  json: False
  xls: False
  mlflow:
    exp_name: testrun
    uri:
  tensorboard:
    enable: True

data:
  fit:
    path: ./test_data.py
    cls: Testset
  eval:
    path:
      - ./data/numpy.npy
      - ./data/numpy2.npy
    type: npy

grader:
  methods: ['acc']
  seed: 666
  batch_size: 100
  unit: epoch
  eval_interval: 1
  remote:
    enable: False
  env:
    type: DDP
    debug: False
    local_size: 2
    world_size: 2
    master_address: 'localhost'
    master_port: '12346'
    backend: gloo

trainer:

  scheme:
    seed: 666
    max_step: 100
    unit: epoch
    save_interval: 10
    save_after_eval: False
    compile: False

  loader:
    shuffle: False
    batch_size: 1000
    pin_memory: False
    num_workers: 0

  env:
     type: DDP
     debug: False
     local_size: 2
     world_size: 2
     global_rank: 0
     master_address: 'localhost'
     master_port: '12345'
     backend: gloo

learner:
  cls: SupremeLearner
  model:
    cls: MyNet
    path: ./model_test.py
    in_features: 256
    out_features: 256
  loss:
    _target_: torch.nn.L1Loss
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.01
  scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    lr_lambda: 0.99
  