defaults:
  - eniat
  - _self_

resume_dir: '/home/user/training_state/221225/'
keep_origin_path: False

task: fit_n_eval
type: torch

logger:
  type: StateLogger
  level: 10
  mlflow:
    enable: True
    uri:
  tensorboard:
    enable: True

data:
  fit:
    path: ./test_data.py
    cls: Testset
  eval:
    path:
      - ./data/numpy.npy
      - ./data/numpy2.npy
    type: npy

grader:
  methods: ['acc']
  unit: epoch
  interval: 1
  device: 0

trainer:
  seed: 666
  batch_size: 1000
  max_step: 100
  unit: epoch
  save_interval: 1
  save_after_eval: True

  env:
     type: single
     dev_id: 0

learner:
  cls: SupremeLearner
  model:
    cls: MyNet
    path: ./model_test.py
    in_features: 256
    out_features: 256
  loss:
    _target_: torch.nn.L1Loss
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.01
  scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    lr_lambda: 0.99
  