working_dir: ${hydra.runtime.output_dir}

resume: False
resume_step:
resume_dir:

accel: False # PyTorch 2.0 compile
num_workers: 0
precision: 16

seed:
batch_size:

init_step: 0
max_step: 0
unit: epoch # ['epoch', 'step']
save_interval: 0
save_after_eval: True

env:
  type: single
  debug: False
  dev_id: 0
  local_rank: 0
  global_rank: 0
  local_size: 1
  world_size: 1
  init_method: 'env://'
  master_address: 'localhost'
  maste_port: 8888
  backend:
  optimizer: zero # ['zero', 'postlocal']