defaults:
  - scheme: default_scheme
  - loader: default_loader
  - env: default_env

resume_model: False
resume_opt: False
resume_step:
resume_dir:

seed:
accel: False # PyTorch 2.0 compile
precision:
dtype:
gradient_scale: False

init_step: 0
max_step: 0
unit: epoch # ['epoch', 'step']
save_interval: 0
save_after_eval: True