defaults:
  - data: default_data
  - logger: default_logger
  - trainer: default_trainer
  - learner: default_learner
  - grader: default_grader
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

init: False
config: []
silent: False
output_dir: ./result

task:
type:

hydra:
  job:
    name: eniat
  run:
    dir: ${output_dir}/${now:%Y_%m_%d}/${now:%H_%M_%S}_${learner.name}_${task}_${hydra.job.override_dirname}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S}_${learner.name}_${trainer.task}_${hydra.job.override_dirname}
  output_subdir: ./.conf #config files
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
