defaults:
  - eniat
  - _self_

log:
  type: StateLogger
  level: 0
  unit: epoch
  interval: 1
  mlflow:
    enable: True
    uri:
  tensorboard:
    enable: True
data:
  fit:
    path: ./test_data.py
    cls: Testset
  eval:
    path:
      - ./data/numpy.npy
      - ./data/numpy2.npy
    type: npy
trainer:

  task: train
  type: torch
  resume: True
  resume_dir: '/home/user/training_state/221225/'

  seed: 666
  batch_size: 1000

  max_step: 100
  unit: epoch

  distributed:
     type: DDP
     debug: False
     local_size: 1
     world_size: 1
     master_address: 'localhost'
     master_port: '12345'
     backend: nccl
     env_set:
     env_copy:

learner:
  cls: SupremeLearner
  path:
  resume: False
  resume_path:
  model:
    cls: MyNet
    path: ./model_test.py
    in_features: 256
    out_features: 256
  loss:
    _target_: torch.nn.L1Loss
  optimizer:
    _target_: torch.optim.AdamW
    lr: 0.01
  scheduler:
    _target_: torch.optim.lr_scheduler.LambdaLR
    lr_lambda: 0.99
  