task:
  output_dir: brr
model:
  structure:
    layers: 8
  optimizer:
    name: AdamW
    options:
      lr: 1-5e
  scheduler:
    name: None
    options:
      lr_decay: 1.0
hyperparameters:
  epoch: 100
  batch_size: 100
  