defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

init: True
config: []
hydra:
  job:
    name: eniat
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
  output_subdir: null #config files
