defaults:
  - data: default_data
  - log: default_logger
  - trainer: default_trainer
  - learner: default_learner
  - _self_

init: False
config: []
hydra:
  job:
    name: eniat
  run:
    dir: ${trainer.env.output_dir}/${now:%Y_%m_%d}/${now:%H_%M_%S}_${learner.name}_${trainer.task}
  sweep:
    dir: ${trainer.env.output_dir}/${now:%Y-%m-%d}
    subdir: ${now:%H-%M-%S}_${learner.name}_${trainer.task}_${hydra.job.override_dirname}
  output_subdir: ./.conf #config files
  job_logging:
    handlers:
      file:
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
